### ISSUE TITLE
A Blog Post on the "rco package"

### ISSUE THREAD

**Issue by adtserapio** [jcrodriguez1989/rco#103]
I have made a blog post on the "rco package" through the RWordpress package to compile my .Rmd files using my personal blog at 
https://coder93.code.blog/2019/12/11/rco-make-your-r-code-run-faster-today/ 

I made a GitHub pages version using `knit` at 
https://pilipino.github.io/pilipino-code-blogger/rco.html

I am waiting first to be approved by R-Bloggers, but I was able to submit my RSS feed to RWeekly to post the article. I think it would also be possible to submit the blog to R-posts and if approved will automatically be uploaded to R-Bloggers. 

![Screen Shot 2019-12-13 at 5 53 40 AM](https://user-images.githubusercontent.com/12228528/70752149-f8703c80-1d6c-11ea-875d-d11282ba93b9.png)

**Comment by jcrodriguez1989** [comment]
thank you very much for your contribution!!
there are some small typos that would be great if you could fix, for example it says " or as an r function " with lowercase R.
Let's see if they aprove your blog post, congrats!! ;)

**Comment by adtserapio** [comment]
@jcrodriguez1989 We're up on R-Weekly Issue 50!! :D

https://rweekly.org/2019-50.html#NewPackages

**Comment by jcrodriguez1989** [comment]
Nice!
Well done!! ;)
thanks!

**Comment by adtserapio** [comment]
@jcrodriguez1989 Hi Sir! We're now up on 

http://r-posts.com/rco-make-your-r-code-run-faster-today/ 
and
https://www.r-bloggers.com/rco-make-your-r-code-run-faster-today/

In fact, `rco` is featured in the front page right now of <a href="r-bloggers.com"> r-bloggers.com</a>. :)

**Comment by jcrodriguez1989** [comment]
Woohoo, great!
thanks @Pilipino , it looks amazing ;)
