### ISSUE TITLE
Blog post on using rco

### ISSUE THREAD

**Issue by olifog** [jcrodriguez1989/rco#105]
Hi! I've created a small blog post demonstrating rco and its uses. It's currently hosted at my [blog](https://oliverfogelin.github.io/rco-Package/), built with jekyll. Since I saw #103 has already been submitted to RWeekly and R-bloggers, I decided against also submitting mine- shall I do so anyway?

Thanks!

**Comment by jcrodriguez1989** [comment]
Your blog post looks amazing!
Please do submit it to RWeekly and R-bloggers.
thank you very much!

**Comment by olifog** [comment]
Thanks- will do!

**Comment by adtserapio** [comment]
@oliverfogelin I think it will never hurt to advertise `rco` twice. 😂

**Comment by olifog** [comment]
@Pilipino Yeah, I hope both our submissions get accepted :)
