### ISSUE TITLE
I dont know what to do please help me

### ISSUE THREAD

**Issue by XDPROAADARSH** [jcrodriguez1989/rco#174]
(This will be fully compatible in 2.1.0) Detected an Administrative Roblox install at C:\Program Files (x86)\Roblox\Versions
Please reinstall Roblox without administrator, as RCO does not have Administrative permissions. | 0xA
If you've already reinstalled and still see this, please delete C:\Program Files (x86)\Roblox

If it still doesn't work, please verify if your 'Program Files (x86)' is set to 'Read-Only' and change it to b

**Comment by XDPROAADARSH** [comment]
please help me

**Comment by jcrodriguez1989** [comment]
Are you sure your issue is with the `{rco}` R package?
