### ISSUE TITLE
rco::optimize_folder

### ISSUE THREAD

**Issue by ColinFay** [jcrodriguez1989/rco#69]
Would be nice to be able to use `{rco}` on a folder, instead of having to list the files: 

``` r
optimize_folder <- function(
  folder,
  optimizers  = "all_optimizers",
  overwrite = FALSE,
  iterations = Inf, 
  pattern = "\\.R$", 
  recursive = TRUE,
  ...
){
  attempt::stop_if_not(
    folder, 
    dir.exists, 
    "The specified folder doesn't exist."
  )
  optimize_files(
    files = list.files(
      path = folder, 
      pattern = pattern, 
      full.names = TRUE, 
      recursive = recursive, 
      ...
    ) %>% purrr::as_vector(), 
    optimizers  = optimizers,
    overwrite = overwrite,
    iterations = iterations
  )
}

optimize_folder("R")

```

Can PR this if you want.

**Comment by ColinFay** [comment]
This would be especially useful when working on packages

**Comment by jcrodriguez1989** [comment]
thanks @ColinFay for your suggestion, feel free to leave any comment at PR #71 .
Just to mention, as a first idea, we had to not use packages outside of R-base, because of the remote possibility that rco could be added to r-base (like the `compiler` package).
Because always think big 😂.
